### ISSUE TITLE
What commits/branch to choose

### ISSUE THREAD

**Issue by Flashaholicturbo** [nathanchance/android-kernel-clang#6]
Hey, thanks for the guidelines for clang. But I still don't no what commits I need to choose for the OnePlus 7 pro kernel. 
Maybe you can help me.
Here is my fork : https://github.com/Flashaholicturbo/android_kernel_oneplus_sm8150

**Comment by nathanchance** [comment]
You don't need any of this for the OnePlus 7 Pro. msm-4.14 and above use clang by default because of https://android.googlesource.com/platform/test/vts-testcase/kernel/+/e1622ae19e0419ceac363d31f7fd53b514b8c218.

**Comment by aIecxs** [comment]
> NOTE: I am not going to write this for beginnings. I assume if you are smart enough to pick some commits, you are smart enough to know how to run git clone and know the paths of your system.

noob question -  where are the patches?
a patch to me looks like [this](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=ce279d374ff315264efcbcef75cc21b9fef8b36f)

> **Getting the Clang patchset**
> 
> kernel/common: 4.4 | 4.9
> 
> msm-4.9-pie - based on the latest Pie branch for the Snapdragon 845 kernel.lnx.4.9.r11-rel

there are several links. the first link is a single commit for the makefile? the latter one looks like kernel source code. do i have to create my own patches based on android-kernel-clang-msm-4.9-pie source code?

**Comment by nathanchance** [comment]
You just need to fetch the repo at the commit linked (such as `git fetch https://android.googlesource.com/kernel/common f0907aa15ed9f9c7541bb244ed3f52c376ced19c`) then cherry-pick the commits/patches (such as `git cherry-pick 3ef0a0c8590b07fa8dfe0adb2bef6cc3baec5261^..f0907aa15ed9f9c7541bb244ed3f52c376ced19c`). In the case of this repo, you need to cherry-pick the patches that were committed by me. I assumed a general working knowledge of `git` (specifically `git cherry-pick`) when writing this because that is what most custom Android kernel developers do with their kernels.
